services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - web-producer
  web-producer:
    container_name: nestjs-producer
    build: ./backend/producer
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql_database
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://rabbitmq-queue:5672
      - RABBITMQ_QUEUE=tasks
    hostname: web-producer
    depends_on:
      - mysql
      - rabbitmq
  web-executor:
    build: ./backend/executor
    environment:
      - MYSQL_HOST=mysql_database
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://rabbitmq-queue:5672
      - RABBITMQ_QUEUE=tasks
    deploy:
      replicas: 2
    depends_on:
      - web-producer
  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: 'nestjs'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:3.13.3
    container_name: rabbitmq-queue
    ports:
      - 5672:5672
      - 15672:15672