networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  minio_data:
    driver: local

services:
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - backend
      - frontend
    ports:
      - '80:80'
    depends_on:
      - web-producer
  web-producer:
    container_name: nestjs-producer
    build: ./backend/producer
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql_database
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://rabbitmq-queue:5672
      - RABBITMQ_QUEUE=tasks
      - LOGTAIL_TOKEN=${PRODUCER_LOGTAIL_TOKEN}
      - CORS_ORIGIN=http://localhost:5173
    hostname: web-producer
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - backend


  web-executor:
    build: ./backend/executor
    environment:
      - MYSQL_HOST=mysql_database
      - MYSQL_PORT=3306
      - RABBITMQ_URL=amqp://rabbitmq-queue
      - RABBITMQ_QUEUE=tasks
      - LOGTAIL_TOKEN=${EXECUTOR_LOGTAIL_TOKEN}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_HOST=minio-filestorage
      - MINIO_DEFAULT_BUCKETS=processed-files
    deploy:
      replicas: 2
    depends_on:
      rabbitmq:
          condition: service_healthy
    networks:
      - backend


  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      - MYSQL_DATABASE=nestjs
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - backend


  rabbitmq:
    image: rabbitmq:3.13.3
    container_name: rabbitmq-queue
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  minio:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_DEFAULT_BUCKETS=processed-files
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SKIP_CLIENT=yes
    container_name: minio-filestorage
    volumes:
      - 'minio_data:/bitnami/minio/data'
    networks:
      - backend
