name: Deploy to 'Timeweb' server

on:
  push:
    branches:
      - main  # Деплой запускается при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.TIMEWEB }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 154.194.53.158 >> ~/.ssh/known_hosts  # Получаем и добавляем ключ сервера

    - name: Copy files to server
      run: |
        scp -r . root@154.194.53.158:~/projects/Aquamarine
    - name: Restart Docker Compose
      run: |
        ssh root@154.194.53.158 "
          cd ~/projects/Aquamarine/src &&
          docker-compose down &&
          docker-compose up -d
        "
